[package]
name = "maolan"
version = "0.0.1"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["tokio"] }
iced_aw = "0.13.0"
maolan-engine = { path = "./engine" }
tokio = { version = "1.49.0", features = ["full"] }
