[package]
name = "maolan"
version = "0.0.1"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["advanced", "image", "tokio"] }
iced_aw = "0.13.0"
iced_drop = { version = "0.2.10", features = ["helpers"] }
iced_fonts = { version = "0.3.0", features = ["lucide"] }
maolan-engine = { path = "./engine" }
vst3 = "0.3"
rfd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
wavers = "1.5.1"
midly = "0.5.3"
symphonia = { version = "0.5.5", default-features = false, features = ["all-formats", "all-codecs"] }
rubato = "0.16.0"
libloading = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
alsa = "0.9.1"

[target.'cfg(target_os = "freebsd")'.dependencies]
nvtree = "0.0.1"
nix = { version = "0.31.1", features = ["ioctl"] }

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
lilv = "0.2.4"
x11-dl = "2.21.0"

[target.'cfg(target_os = "windows")'.dependencies]
cpal = { version = "0.15.3", features = ["asio"] }
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_LibraryLoader", "Win32_UI_WindowsAndMessaging"] }
