[package]
name = "maolan"
version = "0.0.1"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["advanced", "image", "tokio"] }
iced_aw = "0.13.0"
iced_drop = "0.2.6"
maolan-engine = { path = "./engine" }
rfd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
